### PR TITLE
Add kernel patches for oak and update README

### PR DESCRIPTION
**Pull request by chinh4thepro**

### CODE REVIEW

**Comment by chinh4thepro** [comment]
I have a problem, it's not related to linux, but I'm having trouble with the hardware support matrix for the readme formatting properly.

**Comment by chinh4thepro** [comment]
I wasn't sure what it meant by USB gadget, but I tested out a mouse and it worked fine. The camera for me, only worked through the web browser and Gnome's camera manager (Cheese) didn't initiate the camera properly for some reason. Also for sound, you have to manually set it to speakers because it defaults to the HDMI, but not sure if that is specific to gnome.

**Comment by Maccraft123** [comment]
Don't worry too much about hardware support table in readme, I plan on re-doing it anyway

**Comment by chinh4thepro** [comment]
okay

**Pull request merged**
