### PR TITLE
Added script to automatically configure the config file

### PR DESCRIPTION
**Pull request by ENJ1**
I made a small bash script that can fill in the device, distro, suite, etc. It is written pretty badly but does in fact work. 

It must be run using "bash config.sh"

Readme was updated accordingly.

### CODE REVIEW

**Comment by rvstry** [comment]
Without commenting on the usefulness of the script, why not add a shebang `#!/bin/bash` at the start of it?

**Comment by ENJ1** [comment]
> Without commenting on the usefulness of the script, why not add a shebang `#!/bin/bash` at the start of it?

I mean no real reason I couldn't. I just wrote it quickly and forgot.

About the usefulness, personally, I think its useless, but I did see a todo in config file.


When I get home, I'll add that change.

**Comment by Maccraft123** [comment]
it's on purpose that there's no script that would configure cadmium

**Comment by ENJ1** [comment]
> it's on purpose that there's no script that would configure cadmium

May I ask why?

**Pull request closed without merging**
