### PR TITLE
Added support for Elm and Hana (MT8173)

### PR DESCRIPTION
**Pull request by colemancda**
Added support for Elm (Acer Chromebook R13) and Hana (Lenovo  Chromebook 300e).

### CODE REVIEW

**Review by Maccraft123 — APPROVED** [review]
Can you add hardware support of whole mt8173 platform to README.md in a similar way to other boards?

**Comment by Maccraft123** [comment]
After talking to people who know more about mt8173 than I do, there are still some things that need to be changed:
- The baseboard for mt8173 chromebooks is "oak", and not "elm" despite dts files saying otherwise...
- Oak machines use marvell wifi, not atheros
- UCM Files have to be swapped for those suiting oak, https://github.com/hexdump0815/imagebuilder/tree/main/systems/chromebook_oak/extra-files/usr/share/alsa/ucm2/mtk-rt5650

**Comment by colemancda** [comment]
That particular image is not booting for me. Also on boot the google firmware says Elm not Oak.

**Comment by Maccraft123** [comment]
https://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices says the baseboard is oak
change elm baseboard to oak and add hardware support section to readme and i'll merge it after confirming it builds

**Comment by chinh4thepro** [comment]
I tried this but it still boots into a black screen

**Comment by chinh4thepro** [comment]
> That particular image is not booting for me. Also on boot the google firmware says Elm not Oak.

elm is the code name oak is the baseboard name...

**Pull request closed without merging**
